"""
Python code extracted from OAIembed.ipynb
Generated by Project Publisher

Original notebook: 10 cells
Code cells: 10
"""

# Imports
from google.colab import userdata
from openai import OpenAI
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import tiktoken

# Main code
!pip install -qqq openai
key=userdata.get('openai-key')
client = OpenAI(api_key=key)
emb1=client.embeddings.create(
  model="text-embedding-ada-002",
  input="The food was delicious",
  encoding_format="float"
)
print(emb1.data[0].embedding)
print(len(emb1.data[0].embedding))
emb2=client.embeddings.create(
  model="text-embedding-ada-002",
  input="The food was undoubtedly tasty",
  encoding_format="float"
)
print(emb2.data[0].embedding)
print(len(emb2.data[0].embedding))
!pip install -q scikit-learn==1.3.0
cosine_similarity([emb1.data[0].embedding], [emb2.data[0].embedding])
%pip install  tiktoken
encoding = tiktoken.encoding_for_model("babbage-002")
v1=encoding.encode("The food was quite delicious")
encoding = tiktoken.encoding_for_model("babbage-002")
v2=encoding.encode("The food was undoubtedly tasty")
v1_2d = np.array(v1).reshape(1, -1)  # Reshape v1 to a 2D array with 1 row
v2_2d = np.array(v2).reshape(1, -1)  # Reshape v2 to a 2D array with 1 row
similarity = cosine_similarity(v1_2d, v2_2d)
print(similarity)

if __name__ == "__main__":
    # Run the main functionality
    print("Notebook code extracted successfully")